<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-09-27
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the classroom v1 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: Manages classes, rosters, and invitations in Google Classroom.
// API Documentation Link https://developers.google.com/classroom/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/classroom/v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Classroom($client); 
****************************************************/

// Option paramaters can be set as needed.
 $optParams = array(
            
  //'pageToken' => '[YourValue]',  // nextPageTokenvalue returned from a previouslist call,indicating that the subsequent page of results should be returned.The list requestmust be otherwise identical to the one that resulted in this token.
            
  //'orderBy' => '[YourValue]',  // Optional sort ordering for results. A comma-separated list of fields withan optional sort direction keyword. Supported field is `updateTime`.Supported direction keywords are `asc` and `desc`.If not specified, `updateTime desc` is the default behavior.Examples: `updateTime asc`, `updateTime`
            
  //'pageSize' => '[YourValue]',  // Maximum number of items to return. Zero or unspecified indicates that theserver may assign a maximum.The server may return fewer than the specified number of results.
            
  //'announcementStates' => '[YourValue]',  // Restriction on the `state` of announcements returned.If this argument is left unspecified, the default value is `PUBLISHED`.
  'fields' => '*'
);
// Single Request.
$results = announcementsListExample($service, $courseId, $optParams);

// Paginiation Example
do {
    if (!$results->getNextPageToken()) 
		break;

	$optParams['pageToken'] = $results->getNextPageToken();
	$results = filesListExample($service, $courseId, $optParams);	
} while($results->getNextPageToken());  

/**
* Returns a list of announcements that the requester is permitted to view.Course students may only view `PUBLISHED` announcements. Course teachersand domain administrators may view all announcements.This method returns the following error codes:* `PERMISSION_DENIED` if the requesting user is not permitted to accessthe requested course or for access errors.* `INVALID_ARGUMENT` if the request is malformed.* `NOT_FOUND` if the requested course does not exist.
* @service Authenticated Classroom service.
* @optParams Optional paramaters are not required by a request.
* @courseId Identifier of the course.
This identifier can be either the Classroom-assigned identifier or an
alias.
* @return ListAnnouncementsResponse
*/
function announcementsListExample($service, $courseId, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (courseId == null)
			throw new Exception("courseId is required.");
		// Make the request and return the results.
		return $service->announcements->ListAnnouncements($courseId, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
