<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-09-26
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the licensing v1 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: Views and manages licenses for your domain.
// API Documentation Link https://developers.google.com/google-apps/licensing/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/licensing/v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Licensing($client); 
****************************************************/

// Option paramaters can be set as needed.
 $optParams = array(
            
  //'maxResults' => '[YourValue]',  //Maximum number of campaigns to return at one time. Must be positive. Optional. Default value is 100.
            
  //'pageToken' => '[YourValue]',  //Token to fetch the next page.Optional. By default server will return first page
  'fields' => '*'
);
// Single Request.
$results = licenseAssignmentsListForProductAndSkuExample($service, $productId, $skuId, $customerId, $optParams);

// Paginiation Example
do {
    if (!$results->getNextPageToken()) 
		break;

	$optParams['pageToken'] = $results->getNextPageToken();
	$results = filesListExample($service, $productId, $skuId, $customerId, $optParams);	
} while($results->getNextPageToken());  

/**
* List license assignments for given product and sku of the customer.
* @service Authenticated Licensing service.
* @optParams Optional paramaters are not required by a request.
* @customerId CustomerId represents the customer for whom licenseassignments are queried
* @productId Name for product
* @skuId Name for sku
* @return LicenseAssignmentList
*/
function licenseAssignmentsListForProductAndSkuExample($service, $productId, $skuId, $customerId, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (customerId == null)
			throw new Exception("customerId is required.");
		if (productId == null)
			throw new Exception("productId is required.");
		if (skuId == null)
			throw new Exception("skuId is required.");
		// Make the request and return the results.
		return $service->licenseAssignments->ListForProductAndSkuLicenseAssignments($productId, $skuId, $customerId, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
