<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-10-08
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the Games v1 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: The API for Google Play Game Services.
// API Documentation Link https://developers.google.com/games/services/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/games/v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Games($client); 
****************************************************/

// Option paramaters can be set as needed.
 $optParams = array(
            
  //'consistencyToken' => '[YourValue]',  // The last-seen mutation timestamp.
            
  //'language' => '[YourValue]',  // The preferred language to use for strings returned by this method.
            
  //'maxResults' => '[YourValue]',  // The maximum number of leaderboard scores to return in the response. For any response, the actual number of leaderboard scores returned may be less than the specified maxResults.
            
  //'pageToken' => '[YourValue]',  // The token returned by the previous request.
            
  //'resultsAbove' => '[YourValue]',  // The preferred number of scores to return above the player's score. More scores may be returned if the player is at the bottom of the leaderboard; fewer may be returned if the player is at the top. Must be less than or equal to maxResults.
            
  //'returnTopIfAbsent' => '[YourValue]',  // True if the top scores should be returned when the player is not in the leaderboard. Defaults to true.
  'fields' => '*'
);
// Single Request.
$results = scoresListWindowExample($service, $leaderboardId, $collection, $timeSpan, $optParams);

// Paginiation Example
do {
    if (!$results->getNextPageToken()) 
		break;

	$optParams['pageToken'] = $results->getNextPageToken();
	$results = filesListExample($service, $leaderboardId, $collection, $timeSpan, $optParams);	
} while($results->getNextPageToken());  

/**
* Lists the scores in a leaderboard around (and including) a player's score.
* @service Authenticated Games service.
* @optParams Optional paramaters are not required by a request.
* @collection The collection of scores you're requesting.
* @leaderboardId The ID of the leaderboard.
* @timeSpan The time span for the scores and ranks you're requesting.
* @return LeaderboardScores
*/
function scoresListWindowExample($service, $leaderboardId, $collection, $timeSpan, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (collection == null)
			throw new Exception("collection is required.");
		if (leaderboardId == null)
			throw new Exception("leaderboardId is required.");
		if (timeSpan == null)
			throw new Exception("timeSpan is required.");
		// Make the request and return the results.
		return $service->scores->ListWindowScores($leaderboardId, $collection, $timeSpan, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
