<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-09-26
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the reports reports_v1 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: Fetches reports for the administrators of G Suite customers about the usage, collaboration, security, and risk for their users.
// API Documentation Link https://developers.google.com/admin-sdk/reports/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/admin/reports_v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Reports($client); 
****************************************************/

// Option paramaters can be set as needed.
 $optParams = array(
            
  //'actorIpAddress' => '[YourValue]',  //IP Address of host where the event was performed. Supports both IPv4 and IPv6 addresses.
            
  //'customerId' => '[YourValue]',  //Represents the customer for which the data is to be fetched.
            
  //'endTime' => '[YourValue]',  //Return events which occurred at or before this time.
            
  //'eventName' => '[YourValue]',  //Name of the event being queried.
            
  //'filters' => '[YourValue]',  //Event parameters in the form [parameter1 name][operator][parameter1 value],[parameter2 name][operator][parameter2 value],...
            
  //'maxResults' => '[YourValue]',  //Number of activity records to be shown in each page.
            
  //'pageToken' => '[YourValue]',  //Token to specify next page.
            
  //'startTime' => '[YourValue]',  //Return events which occurred at or after this time.
  'fields' => '*'
);
// Single Request.
$results = activitiesListExample($service, $userKey, $applicationName, $optParams);

// Paginiation Example
do {
    if (!$results->getNextPageToken()) 
		break;

	$optParams['pageToken'] = $results->getNextPageToken();
	$results = filesListExample($service, $userKey, $applicationName, $optParams);	
} while($results->getNextPageToken());  

/**
* Retrieves a list of activities for a specific customer and application.
* @service Authenticated Reports service.
* @optParams Optional paramaters are not required by a request.
* @applicationName Application name for which the events are to be retrieved.
* @userKey Represents the profile id or the user email for which the data should be filtered. When 'all' is specified as the userKey, it returns usageReports for all users.
* @return Activities
*/
function activitiesListExample($service, $userKey, $applicationName, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (applicationName == null)
			throw new Exception("applicationName is required.");
		if (userKey == null)
			throw new Exception("userKey is required.");
		// Make the request and return the results.
		return $service->activities->ListActivities($userKey, $applicationName, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
