<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-10-08
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the Play Movies v1 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: Gets the delivery status of titles for Google Play Movies Partners.
// API Documentation Link https://developers.google.com/playmoviespartner/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/playmoviespartner/v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Playmovies($client); 
****************************************************/

// Option paramaters can be set as needed.
 $optParams = array(
            
  //'altId' => '[YourValue]',  // Filter Avails that match a case-insensitive, partner-specific custom id.NOTE: this field is deprecated and will be removed on V2; `alt_ids`should be used instead.
            
  //'studioNames' => '[YourValue]',  // See _List methods rules_ for info about this field.
            
  //'territories' => '[YourValue]',  // Filter Avails that match (case-insensitive) any of the given country codes,using the "ISO 3166-1 alpha-2" format (examples: "US", "us", "Us").
            
  //'title' => '[YourValue]',  // Filter that matches Avails with a `title_internal_alias`,`series_title_internal_alias`, `season_title_internal_alias`,or `episode_title_internal_alias` that contains the givencase-insensitive title.
            
  //'pageToken' => '[YourValue]',  // See _List methods rules_ for info about this field.
            
  //'videoIds' => '[YourValue]',  // Filter Avails that match any of the given `video_id`s.
            
  //'pageSize' => '[YourValue]',  // See _List methods rules_ for info about this field.
            
  //'altIds' => '[YourValue]',  // Filter Avails that match (case-insensitive) any of the given partner-specific custom ids.
            
  //'pphNames' => '[YourValue]',  // See _List methods rules_ for info about this field.
  'fields' => '*'
);
// Single Request.
$results = availsListExample($service, $accountId, $optParams);

// Paginiation Example
do {
    if (!$results->getNextPageToken()) 
		break;

	$optParams['pageToken'] = $results->getNextPageToken();
	$results = filesListExample($service, $accountId, $optParams);	
} while($results->getNextPageToken());  

/**
* List Avails owned or managed by the partner.See _Authentication and Authorization rules_ and_List methods rules_ for more information about this method.
* @service Authenticated Playmovies service.
* @optParams Optional paramaters are not required by a request.
* @accountId REQUIRED. See _General rules_ for more information about this field.
* @return ListAvailsResponse
*/
function availsListExample($service, $accountId, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (accountId == null)
			throw new Exception("accountId is required.");
		// Make the request and return the results.
		return $service->avails->ListAvails($accountId, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
