<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-09-25
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the Container v1beta1 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: The Google Container Engine API is used for building and managing container based applications, powered by the open source Kubernetes technology.
// API Documentation Link https://cloud.google.com/container-engine/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/Container/v1beta1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Container($client); 
****************************************************/

print_r(nodePoolsRollbackExample($service, $projectId, $zone, $clusterId, $nodePoolId));

/**
* Roll back the previously Aborted or Failed NodePool upgrade.This will be an no-op if the last upgrade successfully completed.
* @service Authenticated Container service.
* @zone The name of the Google Compute Engine
[zone](/compute/docs/zones#available) in which the cluster
resides.
This field is deprecated, use name instead.
* @clusterId The name of the cluster to rollback.
This field is deprecated, use name instead.
* @nodePoolId The name of the node pool to rollback.
This field is deprecated, use name instead.
* @projectId The Google Developers Console [project ID or project
number](https://support.google.com/cloud/answer/6158840).
This field is deprecated, use name instead.
* @return Operation</returns>
*/
function nodePoolsRollbackExample($service, $projectId, $zone, $clusterId, $nodePoolId)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if (zone == null)
			throw new Exception("zone is required.");
		if (clusterId == null)
			throw new Exception("clusterId is required.");
		if (nodePoolId == null)
			throw new Exception("nodePoolId is required.");
		if (projectId == null)
			throw new Exception("projectId is required.");
		// Make the request and return the results.
		return $service->nodePools->RollbackNodePools($projectId, $zone, $clusterId, $nodePoolId);
	}
	catch (Exception $ex)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
