<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-09-26
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the People Service v1 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: Provides access to information about profiles and contacts.
// API Documentation Link https://developers.google.com/people/
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/people/v1/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Peopleservice($client); 
****************************************************/

// Option paramaters can be set as needed.
 $optParams = array(
            
  //'requestSyncToken' => '[YourValue]',  //Whether the response should include a sync token, which can be used to getall changes since the last request.
            
  //'pageToken' => '[YourValue]',  //The token of the page to be returned.
            
  //'pageSize' => '[YourValue]',  //The number of connections to include in the response. Valid values arebetween 1 and 2000, inclusive. Defaults to 100.
            
  //'requestMask.includeField' => '[YourValue]',  //**Required.** Comma-separated list of person fields to be included in theresponse. Each path should start with `person.`: for example,`person.names` or `person.photos`.
            
  //'syncToken' => '[YourValue]',  //A sync token, returned by a previous call to `people.connections.list`.Only resources changed since the sync token was created will be returned.
            
  //'personFields' => '[YourValue]',  //**Required.** A field mask to restrict which fields on each person arereturned. Valid values are:* addresses* ageRanges* biographies* birthdays* braggingRights* coverPhotos* emailAddresses* events* genders* imClients* interests* locales* memberships* metadata* names* nicknames* occupations* organizations* phoneNumbers* photos* relations* relationshipInterests* relationshipStatuses* residences* skills* taglines* urls
            
  //'sortOrder' => '[YourValue]',  //The order in which the connections should be sorted. Defaults to`LAST_MODIFIED_ASCENDING`.
  'fields' => '*'
);
// Single Request.
$results = connectionsListExample($service, $resourceName, $optParams);

// Paginiation Example
do {
    if (!$results->getNextPageToken()) 
		break;

	$optParams['pageToken'] = $results->getNextPageToken();
	$results = filesListExample($service, $resourceName, $optParams);	
} while($results->getNextPageToken());  

/**
* Provides a list of the authenticated user's contacts merged with anyconnected profiles.<br>The request throws a 400 error if 'personFields' is not specified.
* @service Authenticated Peopleservice service.
* @optParams Optional paramaters are not required by a request.
* @resourceName The resource name to return connections for. Only `people/me` is valid.
* @return ListConnectionsResponse
*/
function connectionsListExample($service, $resourceName, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (resourceName == null)
			throw new Exception("resourceName is required.");
		// Make the request and return the results.
		return $service->connections->ListConnections($resourceName, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
