<?php
// Copyright 2017 DAIMTO ([Linda Lawton](https://twitter.com/LindaLawtonDK)) :  [www.daimto.com](http://www.daimto.com/)
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by DAIMTO-Google-apis-Sample-generator 1.0.0
//     Template File Name:  methodTemplate.tt
//     Build date: 2017-10-08
//     PHP generator version: 1.0.0
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------  
// About 
// 
// Unofficial sample for the dataflow v1b3 API for PHP. 
// This sample is designed to be used with the Google PHP client library. (https://github.com/google/google-api-php-client)
// 
// API Description: Manages Google Cloud Dataflow projects on Google Cloud Platform.
// API Documentation Link https://cloud.google.com/dataflow
//
// Discovery Doc  https://www.googleapis.com/discovery/v1/apis/dataflow/v1b3/rest
//
//------------------------------------------------------------------------------
// Installation
//
// The preferred method is via https://getcomposer.org. Follow the installation instructions https://getcomposer.org/doc/00-intro.md 
// if you do not already have composer installed.
//
// Once composer is installed, execute the following command in your project root to install this library:
//
// composer require google/apiclient:^2.0
//
//------------------------------------------------------------------------------  
// Load the Google API PHP Client Library.
require_once __DIR__ . '/vendor/autoload.php';
session_start();

/***************************************************
* Include this line for service account authencation.  Note: Not all APIs support service accounts.  
//require_once __DIR__ . '/ServiceAccount.php';     
* Include the following four lines Oauth2 authencation.
* require_once __DIR__ . '/Oauth2Authentication.php';
* $_SESSION['mainScript'] = basename($_SERVER['PHP_SELF']);   // Oauth2callback.php will return here.
* $client = getGoogleClient();
* $service = new Google_Service_Dataflow($client); 
****************************************************/

// Option paramaters can be set as needed.
 $optParams = array(
            
  //'pageToken' => '[YourValue]',  // If supplied, this should be the value of next_page_token returnedby an earlier call. This will cause the next page of results tobe returned.
            
  //'startTime' => '[YourValue]',  // If specified, return only messages with timestamps >= start_time.The default is the job creation time (i.e. beginning of messages).
            
  //'pageSize' => '[YourValue]',  // If specified, determines the maximum number of messages toreturn.  If unspecified, the service may choose an appropriatedefault, or may return an arbitrarily large number of results.
            
  //'minimumImportance' => '[YourValue]',  // Filter to only get messages with importance >= level
            
  //'location' => '[YourValue]',  // The location which contains the job specified by job_id.
            
  //'endTime' => '[YourValue]',  // Return only messages with timestamps < end_time. The default is now(i.e. return up to the latest messages available).
  'fields' => '*'
);
// Single Request.
$results = messagesListExample($service, $projectId, $jobId, $optParams);

// Paginiation Example
do {
    if (!$results->getNextPageToken()) 
		break;

	$optParams['pageToken'] = $results->getNextPageToken();
	$results = filesListExample($service, $projectId, $jobId, $optParams);	
} while($results->getNextPageToken());  

/**
* Request the job status.
* @service Authenticated Dataflow service.
* @optParams Optional paramaters are not required by a request.
* @jobId The job to get messages about.
* @projectId A project id.
* @return ListJobMessagesResponse
*/
function messagesListExample($service, $projectId, $jobId, $optParams)
{
	try
	{
		// Parameter validation.
		if ($service == null)
			throw new Exception("service is required.");
		if ($optParams == null)
			throw new Exception("optParams is required.");
		if (jobId == null)
			throw new Exception("jobId is required.");
		if (projectId == null)
			throw new Exception("projectId is required.");
		// Make the request and return the results.
		return $service->messages->ListMessages($projectId, $jobId, $optParams);
	}
	catch (Exception $e)
	{
		print "An error occurred: " . $e->getMessage();
	}
}
?>
